<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>jazz</AssemblyName>
    <Description>The jazz command line tool.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JazzHands.Control\JazzHands.Control.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
  </ItemGroup>

</Project>
